name: flutter_lwa_platform_interface
description: A common platform interface for the flutter_lwa plugin.
homepage: https://github.com/ayvazj/flutter_lwa
version: 2.1.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  logging: ^1.0.1
  matcher: ^0.12.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.7
  lints: ^2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"
